/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoyoRouteImport } from './routes/apoyo'
import { Route as BienestarRouteImport } from './routes/bienestar'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as PendientesRouteImport } from './routes/pendientes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as TutoriaRouteImport } from './routes/tutoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoRoute = ApoyoRouteImport.update({
  id: '/apoyo',
  path: '/apoyo',
  getParentRoute: () => rootRouteImport,
} as any)
const BienestarRoute = BienestarRouteImport.update({
  id: '/bienestar',
  path: '/bienestar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const PendientesRoute = PendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const TutoriaRoute = TutoriaRouteImport.update({
  id: '/tutoria',
  path: '/tutoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoyo': typeof ApoyoRoute
  '/bienestar': typeof BienestarRoute
  '/calendario': typeof CalendarioRoute
  '/metas': typeof MetasRoute
  '/pendientes': typeof PendientesRoute
  '/perfil': typeof PerfilRoute
  '/progreso': typeof ProgresoRoute
  '/recursos': typeof RecursosRoute
  '/semana': typeof SemanaRoute
  '/tutoria': typeof TutoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoyo': typeof ApoyoRoute
  '/bienestar': typeof BienestarRoute
  '/calendario': typeof CalendarioRoute
  '/metas': typeof MetasRoute
  '/pendientes': typeof PendientesRoute
  '/perfil': typeof PerfilRoute
  '/progreso': typeof ProgresoRoute
  '/recursos': typeof RecursosRoute
  '/semana': typeof SemanaRoute
  '/tutoria': typeof TutoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoyo': typeof ApoyoRoute
  '/bienestar': typeof BienestarRoute
  '/calendario': typeof CalendarioRoute
  '/metas': typeof MetasRoute
  '/pendientes': typeof PendientesRoute
  '/perfil': typeof PerfilRoute
  '/progreso': typeof ProgresoRoute
  '/recursos': typeof RecursosRoute
  '/semana': typeof SemanaRoute
  '/tutoria': typeof TutoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apoyo'
    | '/bienestar'
    | '/calendario'
    | '/metas'
    | '/pendientes'
    | '/perfil'
    | '/progreso'
    | '/recursos'
    | '/semana'
    | '/tutoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apoyo'
    | '/bienestar'
    | '/calendario'
    | '/metas'
    | '/pendientes'
    | '/perfil'
    | '/progreso'
    | '/recursos'
    | '/semana'
    | '/tutoria'
  id:
    | '__root__'
    | '/'
    | '/apoyo'
    | '/bienestar'
    | '/calendario'
    | '/metas'
    | '/pendientes'
    | '/perfil'
    | '/progreso'
    | '/recursos'
    | '/semana'
    | '/tutoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoyoRoute: typeof ApoyoRoute
  BienestarRoute: typeof BienestarRoute
  CalendarioRoute: typeof CalendarioRoute
  MetasRoute: typeof MetasRoute
  PendientesRoute: typeof PendientesRoute
  PerfilRoute: typeof PerfilRoute
  ProgresoRoute: typeof ProgresoRoute
  RecursosRoute: typeof RecursosRoute
  SemanaRoute: typeof SemanaRoute
  TutoriaRoute: typeof TutoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyo': {
      id: '/apoyo'
      path: '/apoyo'
      fullPath: '/apoyo'
      preLoaderRoute: typeof ApoyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienestar': {
      id: '/bienestar'
      path: '/bienestar'
      fullPath: '/bienestar'
      preLoaderRoute: typeof BienestarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendientes': {
      id: '/pendientes'
      path: '/pendientes'
      fullPath: '/pendientes'
      preLoaderRoute: typeof PendientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutoria': {
      id: '/tutoria'
      path: '/tutoria'
      fullPath: '/tutoria'
      preLoaderRoute: typeof TutoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoyoRoute: ApoyoRoute,
  BienestarRoute: BienestarRoute,
  CalendarioRoute: CalendarioRoute,
  MetasRoute: MetasRoute,
  PendientesRoute: PendientesRoute,
  PerfilRoute: PerfilRoute,
  ProgresoRoute: ProgresoRoute,
  RecursosRoute: RecursosRoute,
  SemanaRoute: SemanaRoute,
  TutoriaRoute: TutoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
